vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/axis_infrastructure_v1_1_0
vlib questa_lib/msim/axis_data_fifo_v2_0_10
vlib questa_lib/msim/fifo_generator_v13_2_8
vlib questa_lib/msim/axi_lite_ipif_v3_0_4
vlib questa_lib/msim/lib_cdc_v1_0_2
vlib questa_lib/msim/interrupt_control_v3_1_4
vlib questa_lib/msim/axi_gpio_v2_0_30
vlib questa_lib/msim/lib_pkg_v1_0_2
vlib questa_lib/msim/lib_fifo_v1_0_17
vlib questa_lib/msim/blk_mem_gen_v8_4_6
vlib questa_lib/msim/lib_bmg_v1_0_15
vlib questa_lib/msim/lib_srl_fifo_v1_0_2
vlib questa_lib/msim/axi_datamover_v5_1_30
vlib questa_lib/msim/axi_vdma_v6_3_16
vlib questa_lib/msim/xlconstant_v1_1_7
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_vip_v1_1_14
vlib questa_lib/msim/processing_system7_vip_v1_0_16
vlib questa_lib/msim/proc_sys_reset_v5_0_13
vlib questa_lib/msim/xlconcat_v2_1_4
vlib questa_lib/msim/v_tc_v6_2_6
vlib questa_lib/msim/v_tc_v6_1_13
vlib questa_lib/msim/v_vid_in_axi4s_v4_0_9
vlib questa_lib/msim/v_axi4s_vid_out_v4_0_16
vlib questa_lib/msim/util_vector_logic_v2_0_2
vlib questa_lib/msim/generic_baseblocks_v2_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_28
vlib questa_lib/msim/axi_data_fifo_v2_1_27
vlib questa_lib/msim/axi_crossbar_v2_1_29
vlib questa_lib/msim/axi_protocol_converter_v2_1_28
vlib questa_lib/msim/axi_clock_converter_v2_1_27

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap axis_infrastructure_v1_1_0 questa_lib/msim/axis_infrastructure_v1_1_0
vmap axis_data_fifo_v2_0_10 questa_lib/msim/axis_data_fifo_v2_0_10
vmap fifo_generator_v13_2_8 questa_lib/msim/fifo_generator_v13_2_8
vmap axi_lite_ipif_v3_0_4 questa_lib/msim/axi_lite_ipif_v3_0_4
vmap lib_cdc_v1_0_2 questa_lib/msim/lib_cdc_v1_0_2
vmap interrupt_control_v3_1_4 questa_lib/msim/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_30 questa_lib/msim/axi_gpio_v2_0_30
vmap lib_pkg_v1_0_2 questa_lib/msim/lib_pkg_v1_0_2
vmap lib_fifo_v1_0_17 questa_lib/msim/lib_fifo_v1_0_17
vmap blk_mem_gen_v8_4_6 questa_lib/msim/blk_mem_gen_v8_4_6
vmap lib_bmg_v1_0_15 questa_lib/msim/lib_bmg_v1_0_15
vmap lib_srl_fifo_v1_0_2 questa_lib/msim/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_30 questa_lib/msim/axi_datamover_v5_1_30
vmap axi_vdma_v6_3_16 questa_lib/msim/axi_vdma_v6_3_16
vmap xlconstant_v1_1_7 questa_lib/msim/xlconstant_v1_1_7
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_14 questa_lib/msim/axi_vip_v1_1_14
vmap processing_system7_vip_v1_0_16 questa_lib/msim/processing_system7_vip_v1_0_16
vmap proc_sys_reset_v5_0_13 questa_lib/msim/proc_sys_reset_v5_0_13
vmap xlconcat_v2_1_4 questa_lib/msim/xlconcat_v2_1_4
vmap v_tc_v6_2_6 questa_lib/msim/v_tc_v6_2_6
vmap v_tc_v6_1_13 questa_lib/msim/v_tc_v6_1_13
vmap v_vid_in_axi4s_v4_0_9 questa_lib/msim/v_vid_in_axi4s_v4_0_9
vmap v_axi4s_vid_out_v4_0_16 questa_lib/msim/v_axi4s_vid_out_v4_0_16
vmap util_vector_logic_v2_0_2 questa_lib/msim/util_vector_logic_v2_0_2
vmap generic_baseblocks_v2_1_0 questa_lib/msim/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_28 questa_lib/msim/axi_register_slice_v2_1_28
vmap axi_data_fifo_v2_1_27 questa_lib/msim/axi_data_fifo_v2_1_27
vmap axi_crossbar_v2_1_29 questa_lib/msim/axi_crossbar_v2_1_29
vmap axi_protocol_converter_v2_1_28 questa_lib/msim/axi_protocol_converter_v2_1_28
vmap axi_clock_converter_v2_1_27 questa_lib/msim/axi_clock_converter_v2_1_27

vlog -work xilinx_vip  -incr -mfcu  -sv -L axi_vip_v1_1_14 -L processing_system7_vip_v1_0_16 -L xilinx_vip "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"E:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr -mfcu  -sv -L axi_vip_v1_1_14 -L processing_system7_vip_v1_0_16 -L xilinx_vip "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"E:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"E:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm  -93  \
"E:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ipshared/40b8/hdl/LineBuffer.vhd" \
"../../../bd/system/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
"../../../bd/system/ip/system_AXI_BayerToRGB_A_0/sim/system_AXI_BayerToRGB_A_0.vhd" \
"../../../bd/system/ip/system_AXI_BayerToRGB_B_0/sim/system_AXI_BayerToRGB_B_0.vhd" \
"../../../bd/system/ipshared/2846/hdl/StoredGammaCoefs.vhd" \
"../../../bd/system/ipshared/2846/hdl/AXI_GammaCorrection.vhd" \
"../../../bd/system/ip/system_AXI_GammaCorrection_A_0/sim/system_AXI_GammaCorrection_A_0.vhd" \
"../../../bd/system/ip/system_AXI_GammaCorrection_B_0/sim/system_AXI_GammaCorrection_B_0.vhd" \

vlog -work axis_infrastructure_v1_1_0  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_10  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/sim/line_buffer.v" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \

vlog -work fifo_generator_v13_2_8  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/cdc_fifo/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_8  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_8  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/cdc_fifo/sim/cdc_fifo.v" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ipshared/af9b/hdl/SyncAsync.vhd" \
"../../../bd/system/ipshared/af9b/hdl/SimpleFIFO.vhd" \
"../../../bd/system/ipshared/af9b/hdl/SyncAsyncReset.vhd" \
"../../../bd/system/ipshared/af9b/hdl/CRC16_behavioral.vhd" \
"../../../bd/system/ipshared/af9b/hdl/ECC.vhd" \
"../../../bd/system/ipshared/af9b/hdl/DebugLib.vhd" \
"../../../bd/system/ipshared/af9b/hdl/LM.vhd" \
"../../../bd/system/ipshared/af9b/hdl/LLP.vhd" \
"../../../bd/system/ipshared/af9b/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
"../../../bd/system/ipshared/af9b/hdl/MIPI_CSI2_Rx.vhd" \
"../../../bd/system/ipshared/af9b/hdl/MIPI_CSI2_RxTop.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_A_0/sim/system_MIPI_CSI_2_RX_A_0.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_B_0/sim/system_MIPI_CSI_2_RX_B_0.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
"../../../bd/system/ipshared/ead7/hdl/DPHY_Pkg.vhd" \
"../../../bd/system/ipshared/ead7/hdl/DebugLib.vhd" \
"../../../bd/system/ipshared/ead7/hdl/HS_Deserializer.vhd" \
"../../../bd/system/ipshared/ead7/hdl/GlitchFilter.vhd" \
"../../../bd/system/ipshared/ead7/hdl/HS_Clocking.vhd" \
"../../../bd/system/ipshared/ead7/hdl/InputBuffer.vhd" \
"../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSFEN.vhd" \
"../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSCNN.vhd" \
"../../../bd/system/ipshared/ead7/hdl/S_AXI_Lite.vhd" \
"../../../bd/system/ipshared/ead7/hdl/MIPI_DPHY_Receiver.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_A_0/sim/system_MIPI_D_PHY_RX_A_0.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_B_0/sim/system_MIPI_D_PHY_RX_B_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_30  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_axi_cama_bta_0/sim/system_axi_cama_bta_0.vhd" \
"../../../bd/system/ip/system_axi_cama_gpio_0/sim/system_axi_cama_gpio_0.vhd" \

vcom -work lib_pkg_v1_0_2  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_fifo_v1_0_17  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_6  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_15  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/3f7c/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_30  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/e959/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_16  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_16  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_axi_vdma_a_0/sim/system_axi_vdma_a_0.vhd" \
"../../../bd/system/ip/system_axi_vdma_b_0/sim/system_axi_vdma_b_0.vhd" \

vlog -work xlconstant_v1_1_7  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_cama_gpio_dir_0/sim/system_cama_gpio_dir_0.v" \
"../../../bd/system/ip/system_cama_gpio_oen_0/sim/system_cama_gpio_oen_0.v" \
"../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \

vlog -work axi_infrastructure_v1_1_0  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_14  -incr -mfcu  -sv -L axi_vip_v1_1_14 -L processing_system7_vip_v1_0_16 -L xilinx_vip "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_16  -incr -mfcu  -sv -L axi_vip_v1_1_14 -L processing_system7_vip_v1_0_16 -L xilinx_vip "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ipshared/69dc/src/rgb2vga.vhd" \
"../../../bd/system/ip/system_rgb2vga_0_0/sim/system_rgb2vga_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_13  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_rst_clk_wiz_0_50M_0/sim/system_rst_clk_wiz_0_50M_0.vhd" \
"../../../bd/system/ip/system_rst_system_150M_0/sim/system_rst_system_150M_0.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/AXIvideo2Mat.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/Block_Mat_exit45_pro.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/fifo_w8_d2_A.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/fifo_w32_d2_A.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/fifo_w32_d3_A.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/Mat2AXIvideo.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/Resize.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/Resize_opr_linear.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/Resize_opr_linearbkb.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/start_for_Mat2AXImb6.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/start_for_Resize_U0.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_ctrl_s_axi.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_mul_jbC.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_mul_kbM.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_mul_lbW.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_sdivhbi.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler_udivibs.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/48e8/hdl/vhdl/video_scaler.vhd" \
"../../../bd/system/ip/system_video_scaler_a_0/sim/system_video_scaler_a_0.vhd" \
"../../../bd/system/ip/system_video_scaler_b_0/sim/system_video_scaler_b_0.vhd" \

vlog -work xlconcat_v2_1_4  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
"../../../bd/system/ip/system_xlconcat_1_0/sim/system_xlconcat_1_0.v" \
"../../../bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_clk_wiz.v" \
"../../../bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.v" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_proc_sys_reset_0_0/sim/system_proc_sys_reset_0_0.vhd" \

vcom -work v_tc_v6_2_6  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0350/hdl/v_tc_v6_2_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/ip/system_v_tc_0_0/sim/system_v_tc_0_0.vhd" \

vcom -work v_tc_v6_1_13  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \

vlog -work v_vid_in_axi4s_v4_0_9  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \

vlog -work v_axi4s_vid_out_v4_0_16  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/c523/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_v_axi4s_vid_out_0_1/sim/system_v_axi4s_vid_out_0_1.v" \
"../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \

vlog -work util_vector_logic_v2_0_2  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_util_vector_logic_0_0/sim/system_util_vector_logic_0_0.v" \

vcom -work xil_defaultlib  -93  \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/942f/hdl/vhdl/incrust_AXILiteS_s_axi.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/942f/hdl/vhdl/incrust_im_esirem_V.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/942f/hdl/vhdl/incrust_im_polytebkb.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/942f/hdl/vhdl/regslice_core.vhd" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/942f/hdl/vhdl/incrust.vhd" \
"../../../bd/system/ip/system_incrust_0_0/sim/system_incrust_0_0.vhd" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_xlconstant_1_0/sim/system_xlconstant_1_0.v" \
"../../../bd/system/ip/system_xlconstant_1_1/sim/system_xlconstant_1_1.v" \
"../../../bd/system/ip/system_hsize_0/sim/system_hsize_0.v" \
"../../../bd/system/ip/system_vsize_0/sim/system_vsize_0.v" \

vlog -work generic_baseblocks_v2_1_0  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_28  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_27  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_29  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_xbar_4/sim/system_xbar_4.v" \
"../../../bd/system/ip/system_xbar_5/sim/system_xbar_5.v" \

vlog -work axi_protocol_converter_v2_1_28  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
"../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
"../../../bd/system/ip/system_s00_regslice_0/sim/system_s00_regslice_0.v" \
"../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \

vlog -work axi_clock_converter_v2_1_27  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../../Pcam_base.gen/sources_1/bd/system/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_A_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/line_buffer/hdl" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_B_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_A_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_B_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_a_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_video_scaler_b_0/drivers/video_scaler_v1_0/src" "+incdir+../../../../Pcam_base.gen/sources_1/bd/system/ip/system_incrust_0_0/drivers/incrust_v1_1/src" "+incdir+E:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
"../../../bd/system/ip/system_auto_cc_0/sim/system_auto_cc_0.v" \
"../../../bd/system/ip/system_auto_cc_1/sim/system_auto_cc_1.v" \

vcom -work xil_defaultlib  -93  \
"../../../bd/system/sim/system.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

