// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _incrust_score_HH_
#define _incrust_score_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "incrust_score_im_bkb.h"
#include "incrust_score_im_cud.h"
#include "incrust_score_im_dEe.h"
#include "incrust_score_im_eOg.h"
#include "incrust_score_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct incrust_score : public sc_module {
    // Port declarations 39
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<24> > s_axis_video_TDATA;
    sc_in< sc_logic > s_axis_video_TVALID;
    sc_out< sc_logic > s_axis_video_TREADY;
    sc_in< sc_lv<3> > s_axis_video_TKEEP;
    sc_in< sc_lv<3> > s_axis_video_TSTRB;
    sc_in< sc_lv<1> > s_axis_video_TUSER;
    sc_in< sc_lv<1> > s_axis_video_TLAST;
    sc_in< sc_lv<1> > s_axis_video_TID;
    sc_in< sc_lv<1> > s_axis_video_TDEST;
    sc_out< sc_lv<24> > m_axis_video_TDATA;
    sc_out< sc_logic > m_axis_video_TVALID;
    sc_in< sc_logic > m_axis_video_TREADY;
    sc_out< sc_lv<3> > m_axis_video_TKEEP;
    sc_out< sc_lv<3> > m_axis_video_TSTRB;
    sc_out< sc_lv<1> > m_axis_video_TUSER;
    sc_out< sc_lv<1> > m_axis_video_TLAST;
    sc_out< sc_lv<1> > m_axis_video_TID;
    sc_out< sc_lv<1> > m_axis_video_TDEST;
    sc_in< sc_lv<32> > hsize_in;
    sc_in< sc_lv<32> > vsize_in;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    incrust_score(sc_module_name name);
    SC_HAS_PROCESS(incrust_score);

    ~incrust_score();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    incrust_score_im_bkb* im_1_V_U;
    incrust_score_im_cud* im_2_V_U;
    incrust_score_im_dEe* im_3_V_U;
    incrust_score_im_eOg* im_0_V_U;
    incrust_score_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* incrust_score_AXILiteS_s_axi_U;
    regslice_both<24>* regslice_both_s_axis_video_V_data_V_U;
    regslice_both<3>* regslice_both_s_axis_video_V_keep_V_U;
    regslice_both<3>* regslice_both_s_axis_video_V_strb_V_U;
    regslice_both<1>* regslice_both_s_axis_video_V_user_V_U;
    regslice_both<1>* regslice_both_s_axis_video_V_last_V_U;
    regslice_both<1>* regslice_both_s_axis_video_V_id_V_U;
    regslice_both<1>* regslice_both_s_axis_video_V_dest_V_U;
    regslice_both<24>* regslice_both_m_axis_video_V_data_V_U;
    regslice_both<3>* regslice_both_m_axis_video_V_keep_V_U;
    regslice_both<3>* regslice_both_m_axis_video_V_strb_V_U;
    regslice_both<1>* regslice_both_m_axis_video_V_user_V_U;
    regslice_both<1>* regslice_both_m_axis_video_V_last_V_U;
    regslice_both<1>* regslice_both_m_axis_video_V_id_V_U;
    regslice_both<1>* regslice_both_m_axis_video_V_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > start_x;
    sc_signal< sc_lv<32> > start_y;
    sc_signal< sc_lv<32> > mode;
    sc_signal< sc_lv<12> > im_1_V_address0;
    sc_signal< sc_logic > im_1_V_ce0;
    sc_signal< sc_lv<17> > im_1_V_q0;
    sc_signal< sc_lv<12> > im_2_V_address0;
    sc_signal< sc_logic > im_2_V_ce0;
    sc_signal< sc_lv<17> > im_2_V_q0;
    sc_signal< sc_lv<12> > im_3_V_address0;
    sc_signal< sc_logic > im_3_V_ce0;
    sc_signal< sc_lv<17> > im_3_V_q0;
    sc_signal< sc_lv<12> > im_0_V_address0;
    sc_signal< sc_logic > im_0_V_ce0;
    sc_signal< sc_lv<17> > im_0_V_q0;
    sc_signal< sc_logic > s_axis_video_TDATA_blk_n;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln23_fu_362_p2;
    sc_signal< sc_logic > m_axis_video_TDATA_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > icmp_ln23_reg_616;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > icmp_ln23_reg_616_pp0_iter1_reg;
    sc_signal< sc_lv<64> > indvar_flatten_reg_221;
    sc_signal< sc_lv<31> > i_0_reg_232;
    sc_signal< sc_lv<32> > pixel_1_reg_243;
    sc_signal< sc_lv<31> > j_0_reg_254;
    sc_signal< sc_lv<32> > start_y_read_reg_569;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > start_x_read_reg_575;
    sc_signal< sc_lv<32> > add_ln31_fu_265_p2;
    sc_signal< sc_lv<32> > add_ln31_reg_585;
    sc_signal< sc_lv<32> > add_ln31_1_fu_271_p2;
    sc_signal< sc_lv<32> > add_ln31_1_reg_590;
    sc_signal< sc_lv<1> > icmp_ln32_fu_277_p2;
    sc_signal< sc_lv<1> > icmp_ln32_reg_596;
    sc_signal< sc_lv<1> > and_ln35_fu_301_p2;
    sc_signal< sc_lv<1> > and_ln35_reg_601;
    sc_signal< sc_lv<1> > and_ln38_fu_319_p2;
    sc_signal< sc_lv<1> > and_ln38_reg_606;
    sc_signal< sc_lv<64> > bound_fu_333_p2;
    sc_signal< sc_lv<64> > bound_reg_611;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_io;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<64> > add_ln23_fu_367_p2;
    sc_signal< sc_lv<31> > select_ln23_3_fu_421_p3;
    sc_signal< sc_lv<24> > empty_reg_630_0;
    sc_signal< sc_lv<3> > tmp_keep_V_reg_635;
    sc_signal< sc_lv<3> > tmp_strb_V_reg_640;
    sc_signal< sc_lv<1> > tmp_user_V_reg_645;
    sc_signal< sc_lv<1> > tmp_last_V_reg_650;
    sc_signal< sc_lv<1> > tmp_id_V_reg_655;
    sc_signal< sc_lv<1> > tmp_dest_V_reg_660;
    sc_signal< sc_lv<1> > and_ln31_fu_487_p2;
    sc_signal< sc_lv<1> > and_ln31_reg_665;
    sc_signal< sc_lv<32> > pixel_2_fu_507_p3;
    sc_signal< sc_lv<31> > j_fu_521_p3;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_lv<64> > sext_ln33_fu_493_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<1> > icmp_ln35_fu_283_p2;
    sc_signal< sc_lv<1> > xor_ln32_fu_295_p2;
    sc_signal< sc_lv<1> > or_ln35_fu_307_p2;
    sc_signal< sc_lv<1> > icmp_ln38_fu_289_p2;
    sc_signal< sc_lv<1> > xor_ln35_fu_313_p2;
    sc_signal< sc_lv<32> > bound_fu_333_p0;
    sc_signal< sc_lv<32> > bound_fu_333_p1;
    sc_signal< sc_lv<32> > zext_ln23_1_fu_339_p1;
    sc_signal< sc_lv<32> > zext_ln26_fu_353_p1;
    sc_signal< sc_lv<31> > add_ln23_1_fu_373_p2;
    sc_signal< sc_lv<32> > zext_ln23_fu_379_p1;
    sc_signal< sc_lv<1> > icmp_ln26_fu_357_p2;
    sc_signal< sc_lv<1> > icmp_ln31_fu_343_p2;
    sc_signal< sc_lv<1> > icmp_ln31_3_fu_383_p2;
    sc_signal< sc_lv<1> > icmp_ln31_1_fu_348_p2;
    sc_signal< sc_lv<1> > icmp_ln31_4_fu_396_p2;
    sc_signal< sc_lv<31> > select_ln23_2_fu_409_p3;
    sc_signal< sc_lv<32> > zext_ln23_2_fu_417_p1;
    sc_signal< sc_lv<1> > icmp_ln31_5_fu_458_p2;
    sc_signal< sc_lv<1> > icmp_ln31_2_fu_453_p2;
    sc_signal< sc_lv<1> > select_ln23_fu_388_p3;
    sc_signal< sc_lv<1> > or_ln31_fu_469_p2;
    sc_signal< sc_lv<1> > xor_ln31_1_fu_463_p2;
    sc_signal< sc_lv<1> > or_ln31_1_fu_475_p2;
    sc_signal< sc_lv<1> > select_ln23_1_fu_401_p3;
    sc_signal< sc_lv<1> > xor_ln31_fu_481_p2;
    sc_signal< sc_lv<32> > pixel_fu_501_p2;
    sc_signal< sc_lv<31> > add_ln26_fu_515_p2;
    sc_signal< sc_lv<17> > select_ln32_fu_532_p3;
    sc_signal< sc_lv<17> > select_ln35_fu_539_p3;
    sc_signal< sc_lv<17> > video_data_V_1_fu_546_p3;
    sc_signal< sc_lv<23> > sext_ln38_fu_553_p1;
    sc_signal< sc_lv<24> > zext_ln38_fu_557_p1;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_data_V_U_apdone_blk;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<24> > s_axis_video_TDATA_int;
    sc_signal< sc_logic > s_axis_video_TVALID_int;
    sc_signal< sc_logic > s_axis_video_TREADY_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
    sc_signal< sc_lv<3> > s_axis_video_TKEEP_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
    sc_signal< sc_lv<3> > s_axis_video_TSTRB_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_user_V_U_apdone_blk;
    sc_signal< sc_lv<1> > s_axis_video_TUSER_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > s_axis_video_TLAST_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_id_V_U_apdone_blk;
    sc_signal< sc_lv<1> > s_axis_video_TID_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
    sc_signal< sc_lv<1> > s_axis_video_TDEST_int;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_s_axis_video_V_dest_V_U_ack_in;
    sc_signal< sc_lv<24> > m_axis_video_TDATA_int;
    sc_signal< sc_logic > m_axis_video_TVALID_int;
    sc_signal< sc_logic > m_axis_video_TREADY_int;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_m_axis_video_V_dest_V_U_vld_out;
    sc_signal< sc_lv<64> > bound_fu_333_p00;
    sc_signal< sc_lv<64> > bound_fu_333_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_32;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<31> ap_const_lv31_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln23_1_fu_373_p2();
    void thread_add_ln23_fu_367_p2();
    void thread_add_ln26_fu_515_p2();
    void thread_add_ln31_1_fu_271_p2();
    void thread_add_ln31_fu_265_p2();
    void thread_and_ln31_fu_487_p2();
    void thread_and_ln35_fu_301_p2();
    void thread_and_ln38_fu_319_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_io();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_rst_n_inv();
    void thread_bound_fu_333_p0();
    void thread_bound_fu_333_p00();
    void thread_bound_fu_333_p1();
    void thread_bound_fu_333_p10();
    void thread_bound_fu_333_p2();
    void thread_icmp_ln23_fu_362_p2();
    void thread_icmp_ln26_fu_357_p2();
    void thread_icmp_ln31_1_fu_348_p2();
    void thread_icmp_ln31_2_fu_453_p2();
    void thread_icmp_ln31_3_fu_383_p2();
    void thread_icmp_ln31_4_fu_396_p2();
    void thread_icmp_ln31_5_fu_458_p2();
    void thread_icmp_ln31_fu_343_p2();
    void thread_icmp_ln32_fu_277_p2();
    void thread_icmp_ln35_fu_283_p2();
    void thread_icmp_ln38_fu_289_p2();
    void thread_im_0_V_address0();
    void thread_im_0_V_ce0();
    void thread_im_1_V_address0();
    void thread_im_1_V_ce0();
    void thread_im_2_V_address0();
    void thread_im_2_V_ce0();
    void thread_im_3_V_address0();
    void thread_im_3_V_ce0();
    void thread_j_fu_521_p3();
    void thread_m_axis_video_TDATA_blk_n();
    void thread_m_axis_video_TDATA_int();
    void thread_m_axis_video_TVALID();
    void thread_m_axis_video_TVALID_int();
    void thread_or_ln31_1_fu_475_p2();
    void thread_or_ln31_fu_469_p2();
    void thread_or_ln35_fu_307_p2();
    void thread_pixel_2_fu_507_p3();
    void thread_pixel_fu_501_p2();
    void thread_s_axis_video_TDATA_blk_n();
    void thread_s_axis_video_TREADY();
    void thread_s_axis_video_TREADY_int();
    void thread_select_ln23_1_fu_401_p3();
    void thread_select_ln23_2_fu_409_p3();
    void thread_select_ln23_3_fu_421_p3();
    void thread_select_ln23_fu_388_p3();
    void thread_select_ln32_fu_532_p3();
    void thread_select_ln35_fu_539_p3();
    void thread_sext_ln33_fu_493_p1();
    void thread_sext_ln38_fu_553_p1();
    void thread_video_data_V_1_fu_546_p3();
    void thread_xor_ln31_1_fu_463_p2();
    void thread_xor_ln31_fu_481_p2();
    void thread_xor_ln32_fu_295_p2();
    void thread_xor_ln35_fu_313_p2();
    void thread_zext_ln23_1_fu_339_p1();
    void thread_zext_ln23_2_fu_417_p1();
    void thread_zext_ln23_fu_379_p1();
    void thread_zext_ln26_fu_353_p1();
    void thread_zext_ln38_fu_557_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
