# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1.xci
# IP: The module: 'system_v_axi4s_vid_out_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1.xci
# IP: The module: 'system_v_axi4s_vid_out_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/vivado_proj/Pcam_Adapter_base/Pcam_Adapter_base.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
